version: '3.8'

services:
  postgres-infra:
    container_name: postgres-infra
    image: postgres:15.2
    volumes:
      - postgres_infra_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: infra
      POSTGRES_USER: infra
      POSTGRES_PASSWORD: infra@123
    ports:
      - "5432:5432"

volumes:
  postgres_infra_data: {}
