# Generated by Django 5.1.3 on 2024-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_remove_studentpno_student_studentspno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentspno',
            name='pno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
